import React, { useState } from 'react';
import { PlayCircle, AlertCircle, Download, Settings } from 'lucide-react';
import FileUpload from './components/FileUpload';
import RawDataView from './components/RawDataView';
import AnalysisResults from './components/AnalysisResults';
import { performFullAnalysis } from './utils/analysis';

const App = () => {
  const [rawData, setRawData] = useState(null);
  const [analysisResults, setAnalysisResults] = useState(null);
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState(null);
  const [activeTab, setActiveTab] = useState('upload');
  const [ionSaturationVoltage, setIonSaturationVoltage] = useState(-80);
  const [showSettings, setShowSettings] = useState(false);

  const handleFileLoad = (data) => {
    setRawData(data);
    setAnalysisResults(null);
    setError(null);
    setActiveTab('raw');
  };

  const runAnalysis = async () => {
    if (!rawData || rawData.length < 10) {
      setError('Insufficient data points for analysis');
      return;
    }

    setProcessing(true);
    setError(null);

    try {
      await new Promise(resolve => setTimeout(resolve, 100));

      const voltage = rawData.map(d => d.voltage);
      const current = rawData.map(d => d.current);

      console.log('Starting analysis...');
      console.log(`Data points: ${voltage.length}`);
      console.log(`Voltage range: ${Math.min(...voltage)} to ${Math.max(...voltage)}`);
      console.log(`Current range: ${Math.min(...current)} to ${Math.max(...current)}`);
      console.log(`Ion saturation voltage threshold: ${ionSaturationVoltage} V`);

      const results = performFullAnalysis(voltage, current, ionSaturationVoltage);

      console.log('Analysis complete!');
      console.log('Results:', results);

      setAnalysisResults(results);
      setActiveTab('results');
    } catch (err) {
      console.error('Analysis error:', err);
      setError('Analysis failed: ' + err.message);
    } finally {
      setProcessing(false);
    }
  };

  const exportResults = () => {
    if (!analysisResults) return;

    const results = {
      analysisParameters: {
        ionSaturationVoltageThreshold: ionSaturationVoltage
      },
      summary: {
        plasmaPotential_V: analysisResults.Vp,
        electronTemperature_eV: analysisResults.Te,
        ionDensity_m3: analysisResults.ni,
        electronDensity_m3: analysisResults.ne,
        densityRatio: analysisResults.ratio,
        ionSaturationCurrent_A: analysisResults.iSat,
        electronSaturationCurrent_A: analysisResults.Ip,
        CL_coefficient_a: analysisResults.a
      },
      iterationHistory: analysisResults.iterationHistory,
      note: 'Generated by Langmuir Probe Analyzer'
    };

    const blob = new Blob([JSON.stringify(results, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `langmuir_analysis_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50">
      <div className="w-full max-w-7xl mx-auto p-6">
        {/* Header */}
        <div className="bg-white rounded-lg shadow-xl p-6 mb-6">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold text-indigo-900 mb-2 flex items-center gap-2">
                <svg className="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
                Langmuir Probe Data Analyzer
              </h1>
              <p className="text-gray-600">
                Advanced plasma diagnostics tool for electron temperature, density analysis, and EEDF calculation
              </p>
            </div>
            <button
              onClick={() => setShowSettings(!showSettings)}
              className="px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors flex items-center gap-2"
            >
              <Settings className="w-5 h-5" />
              Settings
            </button>
          </div>

          {/* Settings Panel */}
          {showSettings && (
            <div className="mt-4 p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg border-2 border-indigo-200">
              <h3 className="font-bold text-indigo-900 mb-3 flex items-center gap-2">
                <Settings className="w-5 h-5" />
                Analysis Parameters
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Ion Saturation Region Threshold (V)
                  </label>
                  <div className="flex items-center gap-3">
                    <input
                      type="number"
                      value={ionSaturationVoltage}
                      onChange={(e) => setIonSaturationVoltage(parseFloat(e.target.value))}
                      step="10"
                      className="w-32 px-3 py-2 border-2 border-indigo-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 font-mono text-lg"
                    />
                    <span className="text-gray-600">V</span>
                  </div>
                  <p className="text-xs text-gray-500 mt-1">
                    Voltage below which data is used for CL model fitting (typically -60 to -100 V)
                  </p>
                </div>
                <div className="bg-white p-3 rounded-lg">
                  <p className="text-sm font-semibold text-gray-700 mb-1">Current Setting:</p>
                  <p className="text-2xl font-bold text-indigo-900 font-mono">V &lt; {ionSaturationVoltage} V</p>
                  <p className="text-xs text-gray-600 mt-1">
                    This region will be used to fit the Chen-Luhmann model for ion current
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Main Content */}
        <div className="bg-white rounded-lg shadow-xl overflow-hidden">
          {/* Tabs */}
          <div className="flex border-b">
            <button
              onClick={() => setActiveTab('upload')}
              className={`px-6 py-3 font-semibold transition-colors ${
                activeTab === 'upload'
                  ? 'bg-indigo-600 text-white border-b-2 border-indigo-600'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              📁 Upload Data
            </button>
            <button
              onClick={() => setActiveTab('raw')}
              disabled={!rawData}
              className={`px-6 py-3 font-semibold transition-colors ${
                activeTab === 'raw'
                  ? 'bg-indigo-600 text-white border-b-2 border-indigo-600'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              } disabled:opacity-50 disabled:cursor-not-allowed`}
            >
              📊 Raw I-V Curve
            </button>
            <button
              onClick={() => setActiveTab('results')}
              disabled={!analysisResults}
              className={`px-6 py-3 font-semibold transition-colors ${
                activeTab === 'results'
                  ? 'bg-indigo-600 text-white border-b-2 border-indigo-600'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              } disabled:opacity-50 disabled:cursor-not-allowed`}
            >
              🔬 Analysis Results
            </button>
          </div>

          {/* Tab Content */}
          <div className="p-6">
            {/* Error Display */}
            {error && (
              <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-semibold text-red-900">Error</p>
                  <p className="text-red-700 text-sm">{error}</p>
                </div>
              </div>
            )}

            {/* Upload Tab */}
            {activeTab === 'upload' && (
              <div>
                <FileUpload
                  onFileLoad={handleFileLoad}
                  dataLoaded={rawData ? rawData.length : null}
                />
                {rawData && (
                  <div className="mt-8 text-center">
                    <button
                      onClick={runAnalysis}
                      disabled={processing}
                      className="px-8 py-4 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-3 mx-auto text-lg font-semibold shadow-lg"
                    >
                      <PlayCircle className="w-6 h-6" />
                      {processing ? (
                        <>
                          <span>Processing...</span>
                          <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                        </>
                      ) : (
                        'Run Full Analysis'
                      )}
                    </button>
                    <p className="text-sm text-gray-500 mt-3">
                      Ion saturation threshold: V &lt; {ionSaturationVoltage} V
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* Raw Data Tab */}
            {activeTab === 'raw' && rawData && (
              <div>
                <RawDataView data={rawData} />
                <div className="mt-6 text-center">
                  <button
                    onClick={runAnalysis}
                    disabled={processing}
                    className="px-8 py-4 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-3 mx-auto text-lg font-semibold shadow-lg"
                  >
                    <PlayCircle className="w-6 h-6" />
                    {processing ? (
                      <>
                        <span>Processing...</span>
                        <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                      </>
                    ) : (
                      'Run Full Analysis'
                    )}
                  </button>
                  <p className="text-sm text-gray-500 mt-3">
                    Ion saturation threshold: V &lt; {ionSaturationVoltage} V
                  </p>
                </div>
              </div>
            )}

            {/* Results Tab */}
            {activeTab === 'results' && analysisResults && (
              <div>
                <div className="flex justify-between items-center mb-6">
                  <h2 className="text-2xl font-bold">Complete Analysis Results</h2>
                  <button
                    onClick={exportResults}
                    className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors flex items-center gap-2"
                  >
                    <Download className="w-4 h-4" />
                    Export Results
                  </button>
                </div>
                <AnalysisResults rawData={rawData} results={analysisResults} ionSaturationVoltage={ionSaturationVoltage} />
              </div>
            )}

            {activeTab === 'results' && !analysisResults && (
              <div className="text-center py-12 text-gray-500">
                <AlertCircle className="w-16 h-16 mx-auto mb-4 opacity-50" />
                <p>No analysis results yet. Please upload data and run analysis.</p>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-6 text-center text-sm text-gray-600">
          <p>Langmuir Probe Analyzer v1.0 | Based on iterative Vp convergence algorithm</p>
          <p className="mt-1">
            Implements: CL Model Ion Current Fitting, Log-Log Intersection Method, EEDF Calculation
          </p>
        </div>
      </div>
    </div>
  );
};

export default App;